# Generated by Django 4.0.5 on 2022-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Insira o nome completo.', max_length=255, verbose_name='Nome Completo')),
                ('mother_name', models.CharField(help_text='Insira o nome da sua mãe completo.', max_length=255, verbose_name='Nome da Mãe Completo')),
                ('cpf', models.CharField(blank=True, help_text='Insira somente número CPF.', max_length=11, null=True, unique=True, verbose_name='Número de CPF')),
                ('adress', models.CharField(blank=True, default='', help_text='Insira o endereço seguido de uma referência que auxilie a encontrar sua localidade.', max_length=512, null=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, default='', help_text='Insira número de telefone com o DDD. (Ex.: 91983243576)', max_length=11, null=True, verbose_name='Telefone')),
            ],
        ),
    ]
